In [5]:
import numpy as np

In [6]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a,b)

[[0 1 2]
 [3 4 5]] [[ 6  7  8]
 [ 9 10 11]]


In [7]:
np.vstack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
a= np.arange(6).reshape(3,2)
b= np.arange(6,12).reshape(2,3)
c= np.dot(a,b)
print(c)

[[ 9 10 11]
 [39 44 49]
 [69 78 87]]


In [15]:
a= np.arange(6).reshape(3,2)
b= np.arange(6,12).reshape(2,3)
c= np.dot(a,b)
sum=np.sum(c)

print(sum)

396
